[package]
name = "nordlicht"
version = "0.1.0"
authors = ["Sebastian Morr <sebastian@morr.cc>"]

[dependencies]
gstreamer = "0.11.0"
gstreamer-app = "0.11.0"
clap = "2.31.2"

[dev-dependencies]
assert_cli = "0.5"
