[package]
name = "timelens"
version = "0.1.0"
authors = ["Sebastian Morr <sebastian@morr.cc>"]
repository = "https://github.com/timelens/timelens"
homepage = "https://timelens.io"
license = "GPL-2.0-or-later"
readme = "README.md"
documentation = "https://timelens.io"
description = "Creates visual timelines from video files"

[dependencies]
gstreamer = "0.11.3"
gstreamer-app = "0.11.2"
clap = "2.31.2"

[dev-dependencies]
assert_cmd = "0.3"
